services:
  postgres:
    image: postgres:17-alpine
    container_name: sentinelforge-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: sentinelforge
      POSTGRES_USER: sentinel
      POSTGRES_PASSWORD: sentinel1

    ports:
      - "5433:5432"

    volumes:
      - sentinelforge_postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sentinel -d sentinelforge"]
      interval: 10s
      timeout: 5s
      retries: 5
  kafka:
    image: apache/kafka:4.1.2
    container_name: sentinelforge-kafka
    restart: unless-stopped
    ports:
      - "9092:9092"
      
volumes:
  sentinelforge_postgres_data: